export const stocks = [
  {
    id: 1,
    symbol: 'AAPL',
    name: 'Apple Inc.',
    price: 190.56,
    change: '+1.23%',
    volume: '45M',
  },
  {
    id: 2,
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    price: 245.33,
    change: '-0.87%',
    volume: '30M',
  },
  {
    id: 3,
    symbol: 'AMZN',
    name: 'Amazon.com, Inc.',
    price: 132.98,
    change: '+0.56%',
    volume: '20M',
  },
  {
    id: 4,
    symbol: 'GOOGL',
    name: 'Alphabet Inc. (Google)',
    price: 2785.67,
    change: '+2.45%',
    volume: '10M',
  },
  {
    id: 5,
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    price: 299.25,
    change: '+1.67%',
    volume: '15M',
  },
  {
    id: 6,
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    price: 351.45,
    change: '-0.58%',
    volume: '12M',
  },
  {
    id: 7,
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    price: 475.33,
    change: '+3.12%',
    volume: '8M',
  },
  {
    id: 8,
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    price: 421.22,
    change: '+0.98%',
    volume: '20M',
  },
  {
    id: 9,
    symbol: 'BA',
    name: 'Boeing Company',
    price: 229.56,
    change: '-0.65%',
    volume: '6M',
  },
  {
    id: 10,
    symbol: 'DIS',
    name: 'The Walt Disney Company',
    price: 186.34,
    change: '+1.12%',
    volume: '5M',
  },
  {
    id: 11,
    symbol: 'NFLX',
    name: 'Netflix, Inc.',
    price: 510.12,
    change: '-1.45%',
    volume: '7M',
  },
  {
    id: 12,
    symbol: 'INTC',
    name: 'Intel Corporation',
    price: 57.88,
    change: '-0.75%',
    volume: '25M',
  },
  {
    id: 13,
    symbol: 'AMD',
    name: 'Advanced Micro Devices, Inc.',
    price: 116.67,
    change: '+2.89%',
    volume: '9M',
  },
  {
    id: 14,
    symbol: 'PYPL',
    name: 'PayPal Holdings, Inc.',
    price: 297.85,
    change: '+0.34%',
    volume: '18M',
  },
  {
    id: 15,
    symbol: 'V',
    name: 'Visa Inc.',
    price: 240.11,
    change: '+0.76%',
    volume: '14M',
  },
  {
    id: 16,
    symbol: 'JNJ',
    name: 'Johnson & Johnson',
    price: 167.98,
    change: '+0.95%',
    volume: '22M',
  },
  {
    id: 17,
    symbol: 'PFE',
    name: 'Pfizer Inc.',
    price: 43.67,
    change: '-0.22%',
    volume: '16M',
  },
  {
    id: 18,
    symbol: 'GM',
    name: 'General Motors Company',
    price: 41.88,
    change: '+1.78%',
    volume: '11M',
  },
  {
    id: 19,
    symbol: 'CVX',
    name: 'Chevron Corporation',
    price: 169.67,
    change: '+0.45%',
    volume: '5M',
  },
  {
    id: 20,
    symbol: 'KO',
    name: 'Coca-Cola Company',
    price: 59.55,
    change: '+0.65%',
    volume: '13M',
  },
];
